Repository ablecloud-team/ablestack-monitor, pull requests merged in 2021-09, with the labels that each got.

#38 wall template 수정 및 초기 db 생성
  data/grafana.db
  wall-template/admin/ccvm_details.json
  wall-template/admin/host_details.json
  wall-template/admin/host_overall.json
  wall-template/admin/overall.json
  wall-template/admin/scvm_details.json
  wall-template/admin/uservm_details.json
  wall-template/admin/uservm_overall.json
  wall-template/alert/ccvm_alert.json
  wall-template/alert/host_alert.json
  wall-template/alert/scvm_alert.json
  wall-template/user/uservm_details.json
Labels: enhancement

#43 서비스 시작 파이썬 프로그램 추가
  python/config_prometheus.py
  python/start_services.py
Labels: enhancement

#44 호스트 네트워크 연결 확인 프로그램 추가, grafana 서비스 재시작 로직 추가, 파일 경로 수정 등
  python/config_smtp.py
  python/create_admin_apikey.py
  python/create_noti_channel.py
  python/host_ping_test.py
  python/test_noti_channel.py
  python/update_noti_channel.py
  python/update_noti_json.py
Labels: enhancement

#47 cube, scvm에 blackbox_exporter 포트 삭제, mold smtp 설정 추가 개발
  python/config_prometheus.py
  python/config_smtp.py
  python/start_services.py
Labels: bug, enhancement

#49 prometheus 설정 소스 코드 변경 및 추가
  python/config_wall.py
Labels: enhancement

#52 Wall 서비스 구성 파일(config_wall.py) 테스트 코드 삭제
  python/config_wall.py
Labels: bug

#53 Wall 서비스 배포 시 서비스 이름이 잘못되어 구성에 실패하는 문제 해결
  python/config_smtp.py
Labels: bug

#57 Wall 서비스 배포 단계의 Yaml 파일 로더 방식 변경
  python/config_wall.py
Labels: enhancement

#58 skydive.yml 파일을 설정하는 파일입니다.
  python/config_skydive.py
Labels: enhancement

#60 wall 모니터링 구성시 smtp 세팅할 경우 mold에도 자동 세팅 기능 버그
  python/config_smtp.py
Labels: enhancement

#61 1. config_skydive.py 파일의 소스 코드 수정 하였습니다.
  python/config_skydive.py
Labels: enhancement

#63 libvirt-exporter mold 비밀번호 암화화 기능 설명 추가
  libvirt-exporter/encryption/README.md
Labels: enhancement
