Repository ablecloud-team/ablestack-monitor, pull requests merged in 2022-10, with the labels that each got.

#85 Prometheus 데이터 수집 최대 90일, 저장 용량 최대 60GB 까지 수집 가능하도록 설정 변경
  systemds/vm/prometheus.service
Labels: enhancement

#86 호스트 추가 시, netdive 설정 변경
  python/config_wall.py
Labels: bug, enhancement

#87 모니터링센터 설정 정보 업데이트 버그 수정
  python/config_netdive.py
  python/config_wall.py
Labels: bug

#88 [netdive] [버그] ssh 명령 체크 로직 추가
  python/config_netdive.py
Labels: bug

#89 모니터링 센터 정보 업데이트 오류가 정상적으로 발생하지 않던 문제 해결
  python/config_wall.py
Labels: bug
